# Configuration file for colcon2deb - Using custom Dockerfile
version: 1

# Docker configuration (required)
docker:
  # Build from Dockerfile
  # For pre-configured Dockerfiles, see: https://github.com/NEWSLabNTU/autoware-build-images
  dockerfile: ./docker/2025.02/amd64/Dockerfile
  image_name: colcon2deb_autoware_builder  # optional, name for built image

# Output configuration (required)
output:
  directory: ./output  # Where to place built .deb files

# Package configurations (required)
packages:
  directory: ./config  # Directory containing package-specific debian/ folders

# Build options (optional)
build:
  ros_distro: humble  # auto-detected if not specified
  parallel_jobs: 8    # defaults to nproc
  skip_tests: true    # defaults to false