# Configuration file for colcon2deb
version: 1

# Docker configuration (required)
docker:
  # Option 1: Use existing image
  # image: ros:humble-ros-base

  # Option 2: Build from Dockerfile
  dockerfile: ./Dockerfile
  # build_context: .  # optional, defaults to dockerfile's directory
  # image_name: colcon2deb_builder  # optional, name for built image

# Output configuration (required)
output:
  directory: ./output  # Where to place built .deb files

# Package configurations (required)
packages:
  directory: ./config  # Directory containing package-specific debian/ folders

# Build options (optional)
build:
  ros_distro: humble  # auto-detected if not specified
  parallel_jobs: 8    # defaults to nproc
  skip_tests: true    # defaults to false
