version: 1

# Docker configuration
docker:
  # Always prefer remote URLs to avoid maintaining Dockerfiles locally
  dockerfile: https://raw.githubusercontent.com/NEWSLabNTU/autoware-build-images/refs/heads/main/2025.02/amd64/Dockerfile

  # Optional: Custom image name for caching
  image_name: autoware-0.45.1-builder

# Output configuration with descriptive name
output:
  directory: ./build

# Package configurations with descriptive name
packages:
  directory: ./debian-overrides

# Build options
build:
  ros_distro: humble
  parallel_jobs: 8
  skip_tests: true
